### ISSUE TITLE
Add redirects individually does not work

### ISSUE THREAD

**Issue by walter74ucla** [Automattic/WPCOM-Legacy-Redirector#113]
From the Wiki...
There are three ways to create redirects:

1. Adding redirects from WordPress Admin Visit the Redirect Manager → Add Redirect WP Admin screen and add redirects individually.
=================================================================================================
When we follow step 1, there is no option to input a "to" for 
Relative Path: /redirect_from/,**/redirect_to**
Post ID: /redirect_from/,**123(redirect_to_post_id)**
URL: /redirect_from/,**https://site.com(redirect_to_url)**

**Comment by GaryJones** [comment]
@walter74ucla Did you see the Add Redirect submenu item?

<img width="797" alt="Screenshot 2023-06-28 at 02 27 18" src="https://github.com/Automattic/WPCOM-Legacy-Redirector/assets/88371/1632a20e-4426-4f4d-972e-ad70488a20b8">

**Comment by walter74ucla** [comment]
Yes, I see it now.  We had Redirect Manager as a submenu of Tools, so the Add Redirect page did not render.  It is not possible to create third level menu in admin panel.  Removing it from the Tools submenu let me see it on the Admin screen.

Thanks for checking in Gary.
