### ISSUE TITLE
Remove the deprecated wpcom_vip_get_page_by_path function

### ISSUE THREAD

**Issue by BrookeDot** [Automattic/WPCOM-Legacy-Redirector#134]
WordPress 6.1 added caching to `get_page_by_path`. As such we have deprecated the VIP specific use of the `wpcom_vip_get_page_by_path` helper function:
- https://github.com/Automattic/vip-go-mu-plugins/commit/784f4a674cda8f4cd42b605743e68fe9a2daa816
- https://docs.wpvip.com/caching/uncached-functions/#h-previously-uncached-wordpress-core-functions 

This plugin calls the function here:
https://github.com/Automattic/WPCOM-Legacy-Redirector/blob/eeb5536f7bed699f9ce61e2db8bac9eff973376a/includes/class-wpcom-legacy-redirector.php#L364-L366

**Comment by GaryJones** [comment]
> WordPress 6.1 added caching to `get_page_by_path`

No it didn't - it got reverted: https://core.trac.wordpress.org/ticket/56689#comment:19

Other than a differently named cache group, and a couple of coding standards changes, there's [no difference](https://www.diffchecker.com/zSw0LXvn/) between the [`get_page_by_path()` for WP 6.0.9](https://github.com/WordPress/wordpress-develop/blob/14e986f7b762b94feb714a9bcf1e1a027096ed0d/src/wp-includes/post.php#L5628-L5709), and [`get_page_by_path()` for WP 6.6.2](https://github.com/WordPress/wordpress-develop/blob/b42f5f95417413ee6b05ef389e21b3a0d61d3370/src/wp-includes/post.php#L5847-L5928).

The function that did change in WP 6.1 was `get_page_by_title()` (by _title_, not _path_).

**Comment by GaryJones** [comment]
Re-opening after some untangling.

- Caching was added to `get_page_by_path()` via https://core.trac.wordpress.org/ticket/36711 in WP 4.6.0.
- Here's what it looks like today (WP 6.6.2): https://github.com/WordPress/wordpress-develop/blob/b42f5f95417413ee6b05ef389e21b3a0d61d3370/src/wp-includes/post.php#L5847-L5928 (very little changed).
- The confusing bit is that the effort to make the function use WP_Query (adds priming of caches) internally is the bit that was tried and reverted in https://core.trac.wordpress.org/ticket/56689#comment:19 for WP 6.1.
- Here's where we changed vip-go-mu-plugins on this: https://github.com/Automattic/vip-go-mu-plugins/pull/5224/files?w=1
  Looking at [what was removed](https://github.com/Automattic/vip-go-mu-plugins/pull/5224/files?w=1#diff-bb91099b3c443664b47de9672cd06fad53675053c1e7e46085f39a94821e39f3L162-L179) (doing a version compare for 6.1, creating a cache key, checking the cache and getting the path by page), it's basically the same as what core WP now does. So the removal is good, but the deprecated function warning needs the version amending.
- That means that the effort to remove the VIP function from this plugin makes sense, but that the version doesn't need bumping.
