### ISSUE TITLE
Add ability to white list query params that should pass through on redirects

### ISSUE THREAD

**Issue by mdbitz** [Automattic/WPCOM-Legacy-Redirector#20]
As part of #63905-z we had the interesting request that legacy redirects should ignore utm_* parameters so that they don't get stripped when redirects occur. 

Per discussion in https://github.com/Automattic/WPCOM-Legacy-Redirector/pull/14 it was determined that whitelisting of params would be an ideal solution so that users can allow campaign and other params to be passed through to the redirected page.

**Comment by GaryJones** [comment]
Fixed in #21.
