### ISSUE TITLE
Report on non-whitelisted hosts during the import

### ISSUE THREAD

**Issue by david-binda** [Automattic/WPCOM-Legacy-Redirector#31]
As the plugin uses `wp_safe_redirect`, it would be helpful to report any non-whitelisted host which is being imported.

Example implementation:

```
$parsed_url = parse_url( $redirect_being_imported );
if ( true === isset( $parsed_url['host'] ) && false === empty( $parsed_url['host'] ) ) {
    $wpp = parse_url(home_url());
    $allowed_hosts = (array) apply_filters( 'allowed_redirect_hosts', array($wpp['host']), isset($parsed_url['host']) ? $parsed_url['host'] : '' );
    if ( !in_array($parsed_url['host'], $allowed_hosts) && $parsed_url['host'] != strtolower($wpp['host'])) ) {
        WP_CLI::line( sprintf( 'Non whitelisted host is being imported: %s', $parsed_url['host'] ) );
    }
}
```

**Comment by GaryJones** [comment]
Between the `find-domains` command, and [this](https://github.com/Automattic/WPCOM-Legacy-Redirector/blob/4975f09db8973f006757e749ad2077e1ccd3e7dc/includes/class-wpcom-legacy-redirector.php#L172), I think we're covered here.

Feel free to re-open if this is something different.
