### ISSUE TITLE
Error when running CLI command

### ISSUE THREAD

**Issue by kjbenk** [Automattic/WPCOM-Legacy-Redirector#47]
When calling the `import-from-meta` CLI command I get this error ```Redirect is pointing to a Post ID that does not exist.```

After doing some research it appears that the `vip_legacy_redirect_parent_id ` function is expecting the `$post` variable to be a `WP_Post` object, when in fact it is sometimes a post ID.

The PR below ensures that the `$post` variable is a `WP_Post` object before trying to access its `post_parent` property.

https://github.com/Automattic/WPCOM-Legacy-Redirector/pull/46

**Comment by GaryJones** [comment]
Fixed in #46.
