### ISSUE TITLE
Use X-Redirect-By header

### ISSUE THREAD

**Issue by GaryJones** [Automattic/WPCOM-Legacy-Redirector#51]
WordPress core includes [a `X-Redirect-By` header](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/pluggable.php#L1251) when `wp_redirect()` or `wp_safe_redirect()` is used. By default, this has a value of `WordPress`.

This plugin has a header of: https://github.com/Automattic/WPCOM-Legacy-Redirector/blob/a822f70fe9eee906e8c26d40358736a8c2810de6/wpcom-legacy-redirector.php#L110

_HIT_ is typically thought of in relation to caching, rather than redirecting, so the use of it here may cause confusion.

Better would be to change https://github.com/Automattic/WPCOM-Legacy-Redirector/blob/a822f70fe9eee906e8c26d40358736a8c2810de6/wpcom-legacy-redirector.php#L112 to add a third arg with a reference to the plugin name.

This would mean that WP 5.1 is the minimum required version.

**Comment by bdtech** [comment]
@GaryJones Would you be opposed to checking the version first to then support the third arg? We can build in backward compatibility without much overhead.

`global $wp_version;
if ( version_compare( $wp_version, '5.1.0', '>=' ) ) {`

**Comment by GaryJones** [comment]
That would be fine.

I'm thinking that come the big refactor (for 2.0.0), we can bring the min requirements up significantly (one or two versions behind the current releases of PHP and WP), at which point, we'll likely have WP 5.1 as a minimum and this version check could be removed again.

**Comment by bdtech** [comment]
Great, @GaryJones - a PR has been submitted.

**Comment by GaryJones** [comment]
Closed in #70.
