### ISSUE TITLE
Improve Documentation for class-wpcom-legacy-redirector.php

### ISSUE THREAD

**Issue by bdtech** [Automattic/WPCOM-Legacy-Redirector#69]
Fill in any gaps for undocumented functions that exist today. Make sure all doc blocks conform to standards. This will also clear up a big chunk of PHPCS warnings. 👍 

https://github.com/Automattic/WPCOM-Legacy-Redirector/blob/develop/includes/class-wpcom-legacy-redirector.php

**Comment by GaryJones** [comment]
Closed via #72.
