### ISSUE TITLE
Utilize Constant for Plugin Slug

### ISSUE THREAD

**Issue by bdtech** [Automattic/WPCOM-Legacy-Redirector#71]
Constant should be defined for the plugin's slug. 

`define( 'WPCOM_LEGACY_REDIRECTOR_PLUGIN_SLUG', 'wpcom-legacy-redirector' );`

There are currently 47 references in the code base to the string `'wpcom-legacy-redirector'`  

i.e. `'not_found'             => __( 'No redirects found.', 'wpcom-legacy-redirector' )
`

**Comment by GaryJones** [comment]
I18n functions should NOT use a constant or variable for the text domain. See https://pascalbirchler.com/text-domain-wordpress-internationalization/

**Comment by bdtech** [comment]
Good read, Gary thank you for sharing that.

There are other instances as well outside of internationalization.

**Comment by GaryJones** [comment]
Closed in #70.
