### ISSUE TITLE
UI: Relative paths in network subsites misleading previews and bypassed validation

### ISSUE THREAD

**Issue by davidsword** [Automattic/WPCOM-Legacy-Redirector#73]
In `develop` branch, I noticed when adding a relative path, the `redirect_*_preview` above the input shows the current sites path and appends the inputs value to it. However once submitted, the subsites path is not included, which may be misleading.

Steps to reproduce:

1. checkout `develop` branch
1. activate and visit the ui of the plugin within a network subsite (say `example.com/subsite1/`)
1. type a FROM relative path of `/testing`
1. notice how the preview above the input includes the current subsite1 path and suggests the redirect FROM will be: `example.com/subsite1/testing/`
1. add a valid TO and hit submit
1. notice the redirect FROM created is `example.com/testing/` instead of the previewed `example.com/subsite1/testing/`

Video: https://io.davidsword.ca/wpcomlegacyredirect.mov

The TO input has the same issue, of previewing the subsite path in the preview, but not including it in the actual stored redirect value. There's an additional oddity where if the subsite path isn't included (which will result in a broken link), the link validation does not catch it and it shows as a valid link.

Video: https://io.davidsword.ca/wpcomlegacyredirect2.mov

**Comment by GaryJones** [comment]
Closed in #93.
