### ISSUE TITLE
Submit to packagist

### ISSUE THREAD

**Issue by jenkoian** [Automattic/WPCOM-Legacy-Redirector#75]
For ease of installation. There is currently a bootleg version (https://packagist.org/packages/aaronholbrook/wpcom-legacy-redirector) but would be good to get the proper version on packagist. 

Some similar requests to automattic repos for reference

- https://github.com/woocommerce/wc-smooth-generator/issues/21
- https://github.com/Automattic/vip-go-mu-plugins/issues/1193

**Comment by GaryJones** [comment]
Apologies @jenkoian - I've only just seen this!

I've added https://packagist.org/packages/automattic/wpcom-legacy-redirector/
